# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Push Docker Image'
          script:
            - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
            - docker build -t $DOCKER_HUB_USERNAME/bifrost-relayer-bot:latest .
            - docker push $DOCKER_HUB_USERNAME/bifrost-relayer-bot:latest
          services:
            - docker


      - step:
          name: 'Deploy'
          script:
            - touch .env
            - echo "TELEGRAM_BOT_TOKEN= $TELEGRAM_BOT_TOKEN" ; echo "chat_id= $chat_id" ; echo "group_id= $group_id" >> .env
            # - echo "chat_id= $chat_id" >> .env
            # - echo "group_id= $group_id" >> .env
            - cat .env
            - docker pull cpsehun/bifrost-relayer-bot:latest
            - docker image ls
            - sudo curl -SL https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
            - sudo chmod +x /usr/local/bin/docker-compose
            - export DOCKER_BUILDKIT=0
            - docker-compose --version
            - docker-compose up -d
            # - docker-compose up -d
            # - docker ps -a
            # - docker logs -f
          services:
            - docker
          

    
          



