# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Push Docker Image'
          script:
            - docker build -t bifrost-relayer-bot .
          services:
            - docker

      - step:
          name: 'docker-compose up'
          script:
            - sudo apt-get update
            - sudo apt-get install docker-compose-plugin
            - docker network create dockernet
            - docker-compose up -d
            - docker ps -a
          services:
            - docker
          
# definitions:
#     services:
#         customdocker:
#             image: docker/compose:1.28.5

      # - step:
      #     name: 'docker-compose up'
      #     script:
      #       - cp env-example .env
      #       - vim .env
      #       - echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}" >> .env
      #       - echo "chat_id=${chat_id}" >> .env
      #       - echo "group_id=${group_id}" >> .env


